### ISSUE TITLE
More Row is displayed when the conten is short at 10 rows

### ISSUE THREAD

**Issue by xiaodaigh** [pdeffebach/FloatingTableView.jl#11]
![image](https://user-images.githubusercontent.com/4497189/90357597-dca8fd00-e096-11ea-9c28-03de51ca6020.png)

My dataframe only has 3 rows but more Row id are printed to the left.

**Comment by pdeffebach** [comment]
It shows up using IJulia as well, so it's a TableViews issue. I filed the same thing a few weeks ago [here](https://github.com/JuliaComputing/TableView.jl/issues/46).
