### ISSUE TITLE
view several tables?

### ISSUE THREAD

**Issue by PaulSoderlind** [pdeffebach/FloatingTableView.jl#18]
I just discovered your package. I had something similar in my box, but without the nice `CurrentWin`.

Still, it is sometimes useful to view (compare) two tables. I guess that could easily be implemented in your `browse()` by adding a keyword `reuseWindow` or something.

**Comment by pdeffebach** [comment]
Yeah that's a good idea. I guess I was emulating Stata a bit too much!

Ill see if I can find a way to make that somewhat performant as well.
